import { v4 as uuidv4 } from "uuid";

export const BuildingType = {
  id: uuidv4(),
  level: 1,
  question: "Building Type",
  answer: "",
  type: "DROPDOWN",
  col: 6,
  mandatory: true,
  option: [
    "Apartment/Condo",
    "Single Family House",
    "Multi Family House",
    "Townhouse",
    "Gated Community",
    "Commercial Space",
  ],
  subQuestion: [
    {
      id: uuidv4(),
      level: 2,
      question: "Confirmation of 220V Power Source ?",
      answer: false,
      type: "BOOLEAN",
      col: 12,
      mandatory: true,
      whenToShow: "Apartment/Condo",
      subQuestion: [
        {
          id: uuidv4(),
          level: 2,
          question: "Panel Box Picture",
          answer: [],
          type: "IMAGE",
          col: 12,
          mandatory: true,
          whenToShow: true,
        },
      ],
    },
    {
      id: uuidv4(),
      level: 2,
      question: "Discussed 220w/ customer & included in Scope",
      answer: false,
      type: "BOOLEAN",
      col: 6,
      mandatory: true,
      whenToShow: "Apartment/Condo",
    },
    {
      id: uuidv4(),
      level: 2,
      question: "COI Required for Project",
      answer: "",
      type: "DROPDOWN",
      option: ["Yes", "No", "Unknown"],
      col: 6,
      mandatory: true,
      whenToShow: "Apartment/Condo",
    },
    {
      id: uuidv4(),
      level: 2,
      question: "Apt Parking instructions:",
      answer: "",
      type: "TEXT",
      col: 12,
      mandatory: false,
      whenToShow: "Apartment/Condo",
    },
    {
      id: uuidv4(),
      level: 2,
      question: "Are there any Metal Doors where wood will be scored?",
      answer: false,
      type: "BOOLEAN",
      col: 6,
      mandatory: true,
      whenToShow: "Apartment/Condo",
    },
    {
      id: uuidv4(),
      level: 2,
      question: "Floor Level of Apartment building",
      answer: "",
      type: "TEXT",
      col: 6,
      mandatory: true,
      whenToShow: "Apartment/Condo",
    },
  ],
};
